<?xml version="1.0"?>
<robot>  

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

            <alwaysOn>        false                                 </alwaysOn>
            <legacyMode>      false                                 </legacyMode>
            <updateRate>      20                                    </updateRate>
            <leftJoint>       left_wheel_joint                      </leftJoint>
            <rightJoint>      right_wheel_joint                     </rightJoint>
            <wheelSeparation> ${wheel_separation}                   </wheelSeparation>
            <wheelDiameter>   ${wheel_radius * 2}                   </wheelDiameter>
            <torque>          20                                    </torque>
            <commandTopic>    differential_robot/cmd_vel            </commandTopic>
            <odometryTopic>   differential_robot/odom               </odometryTopic>
            <odometryFrame>   differential_robot_odom               </odometryFrame>
            <robotBaseFrame>  chassis                               </robotBaseFrame>

            <!-- added because of the warnings -->
            <rosDebugLevel>          na      </rosDebugLevel>
            <publishWheelTF>         true    </publishWheelTF>
            <publishOdomTF>          true    </publishOdomTF>
            <publishWheelJointState> false   </publishWheelJointState>
            <wheelAcceleration>      0       </wheelAcceleration>
            <wheelTorque>            5       </wheelTorque>
            <odometrySource>         encoder </odometrySource>
            <publishTf>              1       </publishTf>

        </plugin>
    </gazebo>

    <gazebo reference="sensor_laser">
        <sensor type="ray" name="bad_sensor">
            <pose>        0 0 0 0 0 0 </pose>
            <visualize>   true        </visualize>
            <update_rate> 10          </update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>    360     </samples>
                        <resolution> 1        </resolution>
                        <min_angle>  -3.14159 </min_angle>
                        <max_angle>  3.14159  </max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>        0.10 </min>
                    <max>        10.0 </max>
                    <resolution> 0.05 </resolution>
                </range>
                <noise>
                    <type>   gaussian </type>
                    <mean>   0.0      </mean>
                    <stddev> 0.05     </stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName> differiential_robot/scan </topicName>
                <frameName> sensor_laser              </frameName>
            </plugin>
        </sensor>
    </gazebo>


    <gazebo>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>      true               </alwaysOn>
            <updateRate>    20.0               </updateRate>
            <bodyName>      sensor_laser       </bodyName>
            <topicName>     ground_truth/state </topicName>
            <gaussianNoise> 0.0                </gaussianNoise>
            <xyzOffset>     ${laser_origin_x} ${laser_origin_y} ${laser_origin_z}              </xyzOffset>
            <rpyOffset>     0 0 0              </rpyOffset>
        </plugin>
    </gazebo>

</robot>

